[build]
  builder = "nixpacks"
  buildCommand = "npm run build -- --webpack"

[deploy]
  startCommand = "npx next start -p $PORT"
  healthcheckPath = "/"

[service]
  port = 3000

[mounts]
  data = "/app/data"
